# Blacklist
branches:
  except:
  - gh-pages

# Environment variables
env:
  global:
  - GH_REPO_NAME: glibc
  - GH_REPO_REF: github.com/cheako/glibc.git

services:
- docker

before_install:
- docker build -t glibc .

# Tested on libio-socket-socks-perl 0.73-1, earlier versions may not work.
script:
- docker run glibc

# Generate and deploy documentation
after_success:
- /bin/sh ./.generateDocumentationAndDeploy.sh
